document.addEventListener("mousemove",e=>{const x=e.clientX-window.innerWidth/2;const y=e.clientY-window.innerHeight/2;document.documentElement.style.setProperty("--mx",`${x}px`);document.documentElement.style.setProperty("--my",`${y}px`)});function toggleFaq(button){const item=button.parentElement
;const isOpen=item.classList.contains("active");document.querySelectorAll(".faq-item").forEach(el=>{el.classList.remove("active");const btn=el.querySelector(".faq-header");const answer=el.querySelector(".faq-body");if(btn)btn.setAttribute("aria-expanded","false")
;if(answer)answer.setAttribute("aria-hidden","true")});if(!isOpen){item.classList.add("active");button.setAttribute("aria-expanded","true");const answer=item.querySelector(".faq-body");if(answer)answer.setAttribute("aria-hidden","false")}}(()=>{const canvas=document.getElementById("heroFilm")
;const hero=document.querySelector(".hero-section");if(!canvas||!hero)return;const context=canvas.getContext("2d");const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;let width=0;let height=0;let ratio=1;let animationFrame=0;const particles=Array.from({length:28},(_,index)=>({
x:index*73%101/100,y:index*47%97/100,size:1+index%3,speed:.35+index%5*.08,offset:index*.73}));function resizeFilm(){const bounds=hero.getBoundingClientRect();width=Math.max(1,bounds.width);height=Math.max(1,bounds.height);ratio=Math.min(window.devicePixelRatio||1,1.5);canvas.width=Math.round(width*ratio)
;canvas.height=Math.round(height*ratio);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;context.setTransform(ratio,0,0,ratio,0,0)}function lightRibbon(time,y,amplitude,colorA,colorB,phase){const wave=Math.sin(time*28e-5+phase);const gradient=context.createLinearGradient(0,0,width,0)
;gradient.addColorStop(0,"rgba(255,255,255,0)");gradient.addColorStop(.32,colorA);gradient.addColorStop(.68,colorB);gradient.addColorStop(1,"rgba(255,255,255,0)");context.beginPath();context.moveTo(-width*.08,y+wave*amplitude)
;context.bezierCurveTo(width*.25,y-amplitude*1.4,width*.67,y+amplitude*1.25,width*1.08,y-wave*amplitude);context.strokeStyle=gradient;context.lineWidth=Math.max(42,width*.055);context.lineCap="round";context.stroke()}function renderFilm(time=0){context.clearRect(0,0,width,height)
;const leftGlow=context.createRadialGradient(width*(.08+Math.sin(time*12e-5)*.04),height*.46,0,width*.12,height*.48,Math.max(width,height)*.42);leftGlow.addColorStop(0,"rgba(57,103,242,.15)");leftGlow.addColorStop(.38,"rgba(108,136,255,.07)");leftGlow.addColorStop(1,"rgba(255,255,255,0)")
;context.fillStyle=leftGlow;context.fillRect(0,0,width,height);const topGlow=context.createLinearGradient(width*.38,0,width,height);topGlow.addColorStop(0,"rgba(162,183,255,.07)");topGlow.addColorStop(.46,"rgba(84,128,246,.025)");topGlow.addColorStop(1,"rgba(255,255,255,0)");context.fillStyle=topGlow
;context.fillRect(0,0,width,height);context.save();context.globalCompositeOperation="multiply";context.filter="blur(30px)";lightRibbon(time,height*.22,height*.095,"rgba(74,120,255,.10)","rgba(134,91,255,.08)",0);lightRibbon(time,height*.68,height*.13,"rgba(52,184,240,.07)","rgba(78,108,255,.11)",2.4)
;context.restore();context.save();context.globalCompositeOperation="source-over";particles.forEach((particle,index)=>{const drift=reducedMotion?0:Math.sin(time*22e-5*particle.speed+particle.offset)*19;const x=particle.x*width+drift;const y=particle.y*height+Math.cos(time*17e-5+particle.offset)*11
;const alpha=.08+index%4*.025;context.translate(x,y);context.rotate(time*5e-5+particle.offset);context.fillStyle=`rgba(39,87,210,${alpha})`;context.fillRect(-particle.size,-particle.size,particle.size*2,particle.size*2);context.rotate(-(time*5e-5+particle.offset));context.translate(-x,-y)});context.restore()
;if(!reducedMotion)animationFrame=requestAnimationFrame(renderFilm)}resizeFilm();renderFilm();window.addEventListener("resize",resizeFilm,{passive:true});window.addEventListener("pagehide",()=>cancelAnimationFrame(animationFrame),{once:true})})();(()=>{const wordContainer=document.getElementById("filmWords")
;const timecode=document.getElementById("filmTimecode");const indexLabel=document.getElementById("filmIndex");if(!wordContainer||!timecode||!indexLabel)return;const words=Array.from(wordContainer.querySelectorAll("span"));const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches
;const startedAt=performance.now();let currentWord=0;function updateTimecode(){const elapsed=Math.max(0,performance.now()-startedAt);const minutes=Math.floor(elapsed/6e4);const seconds=Math.floor(elapsed%6e4/1e3);const frames=Math.floor(elapsed%1e3/40)
;timecode.textContent=[minutes,seconds,frames].map(value=>String(value).padStart(2,"0")).join(":")}updateTimecode();if(reducedMotion)return;const wordTimer=window.setInterval(()=>{words[currentWord].classList.remove("active");currentWord=(currentWord+1)%words.length;words[currentWord].classList.add("active")
;indexLabel.textContent=String(currentWord+1).padStart(2,"0")},2200);const timeTimer=window.setInterval(updateTimecode,80);window.addEventListener("pagehide",()=>{window.clearInterval(wordTimer);window.clearInterval(timeTimer)},{once:true})})();(()=>{const hero=document.querySelector(".feeling-hero")
;const stage=document.getElementById("feelingStage");const canvas=document.getElementById("feelingCanvas");const word=document.getElementById("feelingWord");const caption=document.getElementById("feelingCaption");const status=document.getElementById("feelingStatus")
;const startLink=document.getElementById("heroStartLink");const choices=Array.from(document.querySelectorAll(".feeling-choice"));const header=document.querySelector(".site-header");if(!hero||!stage||!canvas||!word||!caption||!status||!startLink||!choices.length)return;const context=canvas.getContext("2d",{
alpha:true});const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const coarsePointer=window.matchMedia("(pointer: coarse)").matches;const feelings={memorable:{title:"MEMORABLE.",caption:"The kind of presence people carry with them.",
colors:[[123,151,255],[170,118,255],[222,234,255]]},trusted:{title:"TRUSTED.",caption:"Clear, reassuring, and easy to choose.",colors:[[96,192,255],[70,126,255],[226,244,255]]},warm:{title:"WARM.",caption:"Human from the very first hello.",colors:[[164,149,255],[239,151,193],[248,222,211]]},unmistakable:{
title:"UNMISTAKABLE.",caption:"A first impression that belongs only to you.",colors:[[109,132,255],[180,100,255],[215,225,255]]}};let width=1;let height=1;let ratio=1;let particles=[];let animationFrame=0;let statusTimer=0;let textTimer=0;let activeFeeling="unmistakable";let previousFeeling="unmistakable"
;let morphStarted=performance.now();const pointer={x:0,y:0,targetX:0,targetY:0,lastX:0,lastY:0,speed:0,lastMove:performance.now(),inside:false};const trails=[];const clamp=(value,min,max)=>Math.min(Math.max(value,min),max);const lerp=(start,end,amount)=>start+(end-start)*amount
;const mixColor=(from,to,amount,alpha=1)=>{const red=Math.round(lerp(from[0],to[0],amount));const green=Math.round(lerp(from[1],to[1],amount));const blue=Math.round(lerp(from[2],to[2],amount));return`rgba(${red}, ${green}, ${blue}, ${alpha})`};const currentPalette=time=>{
const amount=clamp((time-morphStarted)/820,0,1);const previous=feelings[previousFeeling].colors;const next=feelings[activeFeeling].colors;return next.map((color,index)=>[lerp(previous[index][0],color[0],amount),lerp(previous[index][1],color[1],amount),lerp(previous[index][2],color[2],amount)])}
;function createParticles(){const total=width<760?22:44;particles=Array.from({length:total},(_,index)=>({x:index*83%101/100,y:index*41%103/100,size:.65+index%4*.34,phase:index*.79,drift:.28+index%7*.045}))}function resizeCanvas(){const bounds=stage.getBoundingClientRect();width=Math.max(1,bounds.width*1.28)
;height=Math.max(1,bounds.height*1.28);ratio=Math.min(window.devicePixelRatio||1,1.5);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;canvas.style.left=`${-(width-bounds.width)/2}px`
;canvas.style.top=`${-(height-bounds.height)/2}px`;context.setTransform(ratio,0,0,ratio,0,0);pointer.x=pointer.targetX=width*.5;pointer.y=pointer.targetY=height*.5;createParticles()}function drawSoftLight(palette,energy){const radius=Math.max(width,height)*(.28+energy*.12)
;const light=context.createRadialGradient(pointer.x,pointer.y,0,pointer.x,pointer.y,radius);light.addColorStop(0,mixColor(palette[2],palette[0],.18,.18+energy*.14));light.addColorStop(.3,mixColor(palette[0],palette[1],.18,.075+energy*.08));light.addColorStop(1,"rgba(0,0,0,0)");context.fillStyle=light
;context.fillRect(0,0,width,height)}function drawMemories(palette,time,energy){context.save();trails.slice(0,15).forEach((point,index)=>{const life=1-index/16;const radius=10+(1-life)*50+energy*18;context.beginPath();context.strokeStyle=mixColor(palette[0],palette[1],index/15,life*.18)
;context.lineWidth=Math.max(.5,life*1.3);context.arc(point.x,point.y,radius,time*24e-5+index,time*24e-5+index+Math.PI*1.18);context.stroke()});context.restore()}function drawTrusted(palette,energy){context.save();context.lineWidth=.65;for(let index=1;index<7;index+=1){const x=width*index/7
;const bend=(pointer.x-x)*.017*(1+energy);context.beginPath();context.moveTo(x,height*.13);context.quadraticCurveTo(x+bend,height*.5,x,height*.87);context.strokeStyle=mixColor(palette[0],palette[2],.42,.12);context.stroke()}for(let index=2;index<6;index+=1){const y=height*index/7
;const bend=(pointer.y-y)*.014*(1+energy);context.beginPath();context.moveTo(width*.1,y);context.quadraticCurveTo(width*.5,y+bend,width*.9,y);context.strokeStyle=mixColor(palette[1],palette[2],.5,.1);context.stroke()}context.restore()}function drawWarmth(palette,time,energy){context.save()
;context.lineCap="round";for(let index=0;index<5;index+=1){const baseY=height*(.22+index*.14);const sway=Math.sin(time*26e-5+index*1.6)*height*.045;context.beginPath();context.moveTo(-width*.08,baseY+sway);context.bezierCurveTo(width*.2,baseY-sway,pointer.x,pointer.y+sway*.3,width*1.08,baseY-sway*.6)
;context.strokeStyle=mixColor(palette[0],palette[1],index/5,.1+energy*.055);context.lineWidth=1.2+index*.6;context.stroke()}context.restore()}function drawUnmistakable(palette,time,energy){context.save();context.lineCap="round";for(let index=0;index<7;index+=1){const side=index%2===0?-1:1
;const originX=side===-1?-width*.06:width*1.06;const originY=height*(.14+index*.105);const pull=.17+index%3*.035+energy*.08;const destinationX=lerp(originX,pointer.x,pull);const destinationY=lerp(originY,pointer.y,pull);context.beginPath();context.moveTo(originX,originY)
;context.bezierCurveTo(width*.34,originY-height*.13,width*.66,destinationY+height*.12,destinationX,destinationY);context.strokeStyle=mixColor(palette[0],palette[1],index/7,.07+energy*.09);context.lineWidth=.7+index%3*.45;context.stroke()}context.restore()}function drawParticles(palette,time,energy){
context.save();particles.forEach((particle,index)=>{const baseX=particle.x*width+Math.sin(time*18e-5*particle.drift+particle.phase)*18;const baseY=particle.y*height+Math.cos(time*15e-5*particle.drift+particle.phase)*14;const dx=pointer.x-baseX;const dy=pointer.y-baseY
;const distance=Math.max(100,Math.hypot(dx,dy));const force=energy*2400/(distance*distance);const x=baseX-dx*force;const y=baseY-dy*force;const alpha=.085+index%4*.025+energy*.045;context.beginPath();context.fillStyle=mixColor(palette[index%2],palette[2],.24,alpha)
;context.arc(x,y,particle.size+energy*.7,0,Math.PI*2);context.fill()});context.restore()}function paint(time=0){context.clearRect(0,0,width,height);const idle=performance.now()-pointer.lastMove>850;const idleDriftX=idle?Math.sin(time*23e-5)*width*.028:0;const idleDriftY=idle?Math.cos(time*19e-5)*height*.022:0
;pointer.targetX=clamp(pointer.targetX+idleDriftX*.014,0,width);pointer.targetY=clamp(pointer.targetY+idleDriftY*.014,0,height);pointer.x+=(pointer.targetX-pointer.x)*.095;pointer.y+=(pointer.targetY-pointer.y)*.095;pointer.speed*=.91;const energy=clamp(pointer.speed/900+(idle?.055:.09),.04,.72)
;const palette=currentPalette(time);context.save();context.globalCompositeOperation="lighter";drawSoftLight(palette,energy);if(activeFeeling==="memorable")drawMemories(palette,time,energy);if(activeFeeling==="trusted")drawTrusted(palette,energy);if(activeFeeling==="warm")drawWarmth(palette,time,energy)
;if(activeFeeling==="unmistakable")drawUnmistakable(palette,time,energy);drawParticles(palette,time,energy);context.restore();const stageBounds=stage.getBoundingClientRect();const relativeX=pointer.x/width-.5;const relativeY=pointer.y/height-.5;stage.style.setProperty("--stage-x",`${relativeX*24}px`)
;stage.style.setProperty("--stage-y",`${relativeY*19}px`);const dramatic=activeFeeling==="unmistakable"?energy:energy*.28;word.style.setProperty("--word-x",`${relativeX*17*dramatic}px`);word.style.setProperty("--word-y",`${relativeY*13*dramatic}px`)
;word.style.setProperty("--word-rotate",`${relativeX*5*dramatic}deg`);word.style.setProperty("--word-skew",`${relativeY*2.5*dramatic}deg`);word.style.letterSpacing=activeFeeling==="unmistakable"?`${-.075+relativeX*.012*dramatic}em`:"-.075em";stage.dataset.active=activeFeeling
;if(!reducedMotion)animationFrame=requestAnimationFrame(paint)}function setFeeling(feeling,announce=true){const next=feelings[feeling];if(!next||feeling===activeFeeling&&hero.dataset.feeling===feeling)return;previousFeeling=activeFeeling;activeFeeling=feeling;morphStarted=performance.now()
;hero.dataset.feeling=feeling;choices.forEach(choice=>{const active=choice.dataset.feeling===feeling;choice.classList.toggle("is-active",active);choice.setAttribute("aria-pressed",String(active))});word.classList.remove("is-changing");caption.classList.add("is-changing");void word.offsetWidth
;word.textContent=next.title;word.classList.add("is-changing");window.clearTimeout(textTimer);textTimer=window.setTimeout(()=>{caption.textContent=next.caption;caption.classList.remove("is-changing")},170);startLink.href=`start.html?feeling=${encodeURIComponent(feeling)}`;if(announce){
status.textContent="FEELING UPDATED.";status.classList.add("is-visible");window.clearTimeout(statusTimer);statusTimer=window.setTimeout(()=>status.classList.remove("is-visible"),1250)}}choices.forEach(choice=>{choice.addEventListener("click",()=>setFeeling(choice.dataset.feeling))})
;function setPointerPosition(clientX,clientY){const bounds=canvas.getBoundingClientRect();const nextX=(clientX-bounds.left)*width/bounds.width;const nextY=(clientY-bounds.top)*height/bounds.height;const velocity=Math.hypot(nextX-pointer.lastX,nextY-pointer.lastY)
;pointer.speed=clamp(pointer.speed*.42+velocity,0,1200);pointer.lastX=nextX;pointer.lastY=nextY;pointer.targetX=clamp(nextX,0,width);pointer.targetY=clamp(nextY,0,height);pointer.lastMove=performance.now();pointer.inside=true;trails.unshift({x:pointer.targetX,y:pointer.targetY})
;if(trails.length>19)trails.pop()}stage.addEventListener("pointermove",event=>setPointerPosition(event.clientX,event.clientY));stage.addEventListener("pointerleave",()=>{pointer.inside=false;pointer.targetX=width*.5;pointer.targetY=height*.5;pointer.lastMove=0});document.addEventListener("mouseleave",()=>{
pointer.inside=false;pointer.targetX=width*.5;pointer.targetY=height*.5;pointer.lastMove=0});if(coarsePointer){window.addEventListener("deviceorientation",event=>{const tiltX=clamp((event.gamma||0)/45,-.45,.45);const tiltY=clamp((event.beta||0)/60,-.35,.35);pointer.targetX=width*(.5+tiltX*.2)
;pointer.targetY=height*(.5+tiltY*.15)},{passive:true})}function updateScroll(){const progress=clamp(window.scrollY/Math.max(window.innerHeight*.78,1),0,1);hero.style.setProperty("--scroll-progress",progress.toFixed(3));header?.classList.toggle("is-scrolled",window.scrollY>72)}
const cursor=document.getElementById("feCursor");const cursorLabel=document.getElementById("feCursorLabel");if(cursor&&cursorLabel&&!coarsePointer&&!reducedMotion){document.body.classList.add("fe-cursor-enabled");let cursorX=window.innerWidth*.5;let cursorY=window.innerHeight*.5;let cursorTargetX=cursorX
;let cursorTargetY=cursorY;let cursorFrame=0;function moveCursor(){cursorX+=(cursorTargetX-cursorX)*.22;cursorY+=(cursorTargetY-cursorY)*.22;cursor.style.transform=`translate3d(${cursorX}px, ${cursorY}px, 0)`;cursorFrame=requestAnimationFrame(moveCursor)}document.addEventListener("pointermove",event=>{
cursorTargetX=event.clientX;cursorTargetY=event.clientY;cursor.classList.add("is-visible")},{passive:true});document.addEventListener("pointerleave",()=>cursor.classList.remove("is-visible"));document.addEventListener("pointerover",event=>{const target=event.target.closest?.("[data-cursor], .feeling-choice")
;if(!target)return;const label=target.dataset.cursor||"FEEL";cursorLabel.textContent=label;cursor.dataset.kind=label.startsWith("START")?"start":label.startsWith("VIEW")?"view":"feel";cursor.classList.add("is-lens")});document.addEventListener("pointerout",event=>{
const leaving=event.target.closest?.("[data-cursor], .feeling-choice");if(!leaving)return;const entering=event.relatedTarget?.closest?.("[data-cursor], .feeling-choice");if(entering)return;cursor.classList.remove("is-lens")});moveCursor()
;window.addEventListener("pagehide",()=>cancelAnimationFrame(cursorFrame),{once:true})}const projectButton=document.querySelector(".hero-project-button");if(projectButton&&!coarsePointer){projectButton.addEventListener("pointermove",event=>{const bounds=projectButton.getBoundingClientRect()
;const x=(event.clientX-bounds.left)/bounds.width;const y=(event.clientY-bounds.top)/bounds.height;projectButton.style.setProperty("--button-x",`${x*100}%`);projectButton.style.setProperty("--button-y",`${y*100}%`);projectButton.style.setProperty("--magnet-x",`${(x-.5)*7}px`)
;projectButton.style.setProperty("--magnet-y",`${(y-.5)*6}px`)});projectButton.addEventListener("pointerleave",()=>{projectButton.style.setProperty("--magnet-x","0px");projectButton.style.setProperty("--magnet-y","0px")})}resizeCanvas();setFeeling("unmistakable",false);updateScroll();paint()
;window.addEventListener("resize",()=>{resizeCanvas();updateScroll()},{passive:true});window.addEventListener("scroll",updateScroll,{passive:true});window.addEventListener("pagehide",()=>cancelAnimationFrame(animationFrame),{once:true});requestAnimationFrame(()=>{document.body.classList.remove("fe-not-ready")
;document.body.classList.add("fe-ready")})})();(()=>{const hero=document.querySelector(".studio-split-hero");if(!hero)return;const reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const header=document.querySelector(".site-header");let targetProgress=0;let renderedProgress=0
;let animationFrame=0;const renderHero=()=>{animationFrame=0;renderedProgress+=(targetProgress-renderedProgress)*.12;hero.style.setProperty("--split-copy-shift",`${(renderedProgress*-24).toFixed(2)}px`);hero.style.setProperty("--split-panel-shift",`${(renderedProgress*18).toFixed(2)}px`)
;hero.style.setProperty("--split-arc-shift",`${(renderedProgress*-34).toFixed(2)}px`);hero.style.setProperty("--split-mono-shift",`${(renderedProgress*20).toFixed(2)}px`);if(Math.abs(targetProgress-renderedProgress)>.001)animationFrame=requestAnimationFrame(renderHero)};const updateHero=()=>{
const bounds=hero.getBoundingClientRect();targetProgress=Math.max(0,Math.min(1,-bounds.top/(bounds.height*.86)));if(!animationFrame)animationFrame=requestAnimationFrame(renderHero);if(header)header.classList.toggle("is-scrolled",window.scrollY>48)};if(!reduceMotion){
const revealTargets=Array.from(document.querySelectorAll(["main > section:not(.studio-split-hero) .container > *",".journey-step-card",".process-step-item",".faq-item",".final-action-card"].join(",")));const uniqueTargets=[...new Set(revealTargets)].filter(element=>!element.closest(".studio-split-hero"))
;if("IntersectionObserver"in window){document.documentElement.classList.add("scroll-motion-ready");uniqueTargets.forEach((element,index)=>{element.classList.add("motion-item");element.style.setProperty("--motion-delay",`${index%4*120}ms`)});const observer=new IntersectionObserver(entries=>{
entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add("is-visible");observer.unobserve(entry.target)})},{threshold:.18,rootMargin:"0px 0px -12% 0px"});uniqueTargets.forEach(element=>observer.observe(element))}updateHero();window.addEventListener("scroll",updateHero,{passive:true})
;window.addEventListener("resize",updateHero,{passive:true});window.addEventListener("pagehide",()=>cancelAnimationFrame(animationFrame),{once:true})}else if(header){window.addEventListener("scroll",()=>header.classList.toggle("is-scrolled",window.scrollY>48),{passive:true})}})();(()=>{
const card=document.getElementById("projectFlowCard");if(!card)return;const panels=new Map(Array.from(card.querySelectorAll("[data-project-panel]")).map(panel=>[panel.dataset.projectPanel,panel]));const progressBar=document.getElementById("projectProgressBar")
;const progressCount=document.getElementById("projectProgressCount");const status=document.getElementById("projectFlowStatus");const typeChoices=Array.from(card.querySelectorAll("[data-project-type]"));const goalChoices=Array.from(card.querySelectorAll("[data-project-goal]"))
;const typeNext=card.querySelector('[data-project-next="goals"]');const goalsNext=card.querySelector('[data-project-next="details"]');const detailsNext=card.querySelector('[data-project-next="auth"]');const detailsForm=document.getElementById("projectDetailsForm")
;const authForm=document.getElementById("projectAuthForm");const authEmail=document.getElementById("authEmail");const authPassword=document.getElementById("authPassword");const authSubmit=document.getElementById("projectAuthSubmit");const googleButton=document.getElementById("googleAuthButton")
;const authTabs=Array.from(card.querySelectorAll("[data-auth-mode]"));const authHeading=panels.get("auth")?.querySelector("h3");const authDescription=panels.get("auth")?.querySelector(".project-panel-heading p");const authKicker=panels.get("auth")?.querySelector(".project-panel-kicker")
;const authBack=panels.get("auth")?.querySelector("[data-project-back]");const storageKey="marzoftProjectDraft";const intentKey="marzoftProjectIntent";const progressSteps={type:1,goals:2,details:3,auth:4,success:4};const progressLabels={intro:"GETTING STARTED",type:"YOUR VISION",goals:"THE OUTCOME",
details:"YOUR DETAILS",auth:"READY TO SEND",success:"RECEIVED"};const previousPanel={type:"intro",goals:"type",details:"goals",auth:"details"};const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;let currentPanel="intro";let authMode="signup";let authEntry="project"
;let transitionTimer=0;let statusTimer=0;const emptyDraft=()=>({projectType:"",goals:[],story:"",name:"",email:"",whatsapp:"",budget:""});const readDraft=()=>{try{const stored=JSON.parse(sessionStorage.getItem(storageKey)||"null");if(!stored||typeof stored!=="object")return emptyDraft();return{
...emptyDraft(),...stored,goals:Array.isArray(stored.goals)?stored.goals:[]}}catch(error){return emptyDraft()}};let draft=readDraft();const writeDraft=()=>{try{sessionStorage.setItem(storageKey,JSON.stringify(draft))}catch(error){}};const clearDraft=()=>{draft=emptyDraft();try{
sessionStorage.removeItem(storageKey)}catch(error){}};const setStatus=(message="",kind="error",autoClear=true)=>{window.clearTimeout(statusTimer);status.textContent=message;status.classList.toggle("has-message",Boolean(message));status.classList.toggle("is-success",kind==="success");if(message&&autoClear){
statusTimer=window.setTimeout(()=>setStatus("","error",false),kind==="success"?5600:7200)}};const setLoading=loading=>{card.classList.toggle("is-loading",loading);card.setAttribute("aria-busy",String(loading));authSubmit.disabled=loading;googleButton.disabled=loading}
;const hasProjectDraft=()=>Boolean(draft.projectType);const rememberAuthIntent=intent=>{try{sessionStorage.setItem(intentKey,intent)}catch(error){}};const readAuthIntent=()=>{try{return sessionStorage.getItem(intentKey)||""}catch(error){return""}};const updateAuthCopy=()=>{
const projectFlow=authEntry==="project"&&hasProjectDraft();if(authKicker)authKicker.textContent=projectFlow?"SAVE AND SEND YOUR BRIEF":"CLIENT ACCESS";if(authHeading)authHeading.textContent=projectFlow?"Make it yours.":"Welcome back.";if(authDescription){
authDescription.textContent=projectFlow?"Sign in to securely send the request and track every update from your dashboard.":"Sign in to see your requests, progress, messages, and every next step."}if(authBack)authBack.textContent=projectFlow?"← Edit my details":"← Back to project card"
;const label=authMode==="signup"?projectFlow?"Create account & send request":"Create my account":projectFlow?"Sign in & send request":"Sign in to dashboard";authSubmit.innerHTML=`${label} <span>→</span>`;authPassword.autocomplete=authMode==="signup"?"new-password":"current-password"
;authPassword.placeholder=authMode==="signup"?"Minimum 8 characters":"Your password"};const setAuthMode=mode=>{authMode=mode==="signin"?"signin":"signup";authTabs.forEach(tab=>{const active=tab.dataset.authMode===authMode;tab.classList.toggle("is-active",active)
;tab.setAttribute("aria-selected",String(active));tab.tabIndex=active?0:-1});setStatus("","error",false);updateAuthCopy()};const showPanel=name=>{const next=panels.get(name);const current=panels.get(currentPanel);if(!next||next===current)return;window.clearTimeout(transitionTimer);if(current){
current.classList.add("is-leaving");current.classList.remove("is-active");current.setAttribute("aria-hidden","true")}next.classList.add("is-active");next.setAttribute("aria-hidden","false");currentPanel=name;card.classList.toggle("is-started",name!=="intro");const step=progressSteps[name]||1
;progressBar.style.width=`${step*25}%`;progressCount.textContent=progressLabels[name]||"GETTING STARTED";transitionTimer=window.setTimeout(()=>{current?.classList.remove("is-leaving");if(name!=="intro"){const heading=next.querySelector("h3");if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}
}},reducedMotion?0:780)};const restoreDraftToForm=()=>{typeChoices.forEach(choice=>{const selected=choice.dataset.projectType===draft.projectType;choice.classList.toggle("is-selected",selected);choice.setAttribute("aria-pressed",String(selected))});goalChoices.forEach(choice=>{
const selected=draft.goals.includes(choice.dataset.projectGoal);choice.classList.toggle("is-selected",selected);choice.setAttribute("aria-pressed",String(selected))});typeNext.disabled=!draft.projectType;goalsNext.disabled=draft.goals.length===0;document.getElementById("projectStory").value=draft.story
;document.getElementById("projectName").value=draft.name;document.getElementById("projectEmail").value=draft.email;document.getElementById("projectWhatsapp").value=draft.whatsapp;document.getElementById("projectBudget").value=draft.budget;authEmail.value=draft.email};const collectDetails=()=>{
draft.story=document.getElementById("projectStory").value.trim();draft.name=document.getElementById("projectName").value.trim();draft.email=document.getElementById("projectEmail").value.trim();draft.whatsapp=document.getElementById("projectWhatsapp").value.trim()
;draft.budget=document.getElementById("projectBudget").value;authEmail.value=draft.email;writeDraft()};const openProjectFlow=()=>{authEntry="project";setAuthMode("signup");showPanel("type")};card.querySelector("[data-project-open]")?.addEventListener("click",openProjectFlow);typeChoices.forEach(choice=>{
choice.setAttribute("aria-pressed","false");choice.addEventListener("click",()=>{draft.projectType=choice.dataset.projectType;typeChoices.forEach(item=>{const selected=item===choice;item.classList.toggle("is-selected",selected);item.setAttribute("aria-pressed",String(selected))});typeNext.disabled=false
;writeDraft()})});goalChoices.forEach(choice=>{choice.setAttribute("aria-pressed","false");choice.addEventListener("click",()=>{const goal=choice.dataset.projectGoal;const selected=!draft.goals.includes(goal);draft.goals=selected?[...draft.goals,goal]:draft.goals.filter(item=>item!==goal)
;choice.classList.toggle("is-selected",selected);choice.setAttribute("aria-pressed",String(selected));goalsNext.disabled=draft.goals.length===0;writeDraft()})});document.getElementById("projectStory")?.addEventListener("input",event=>{draft.story=event.target.value;writeDraft()})
;typeNext?.addEventListener("click",()=>showPanel("goals"));goalsNext?.addEventListener("click",()=>showPanel("details"));const continueToAuth=()=>{if(!detailsForm.reportValidity())return;collectDetails();authEntry="project";rememberAuthIntent("project");setAuthMode("signup");showPanel("auth")}
;detailsNext?.addEventListener("click",continueToAuth);detailsForm?.addEventListener("submit",event=>{event.preventDefault();continueToAuth()});card.querySelectorAll("[data-project-back]").forEach(button=>{button.addEventListener("click",()=>{if(card.classList.contains("is-loading"))return
;const destination=currentPanel==="auth"&&authEntry==="login"?"intro":previousPanel[currentPanel];if(destination)showPanel(destination)})});authTabs.forEach(tab=>tab.addEventListener("click",()=>setAuthMode(tab.dataset.authMode)));const resolveBackend=()=>{
const facade=window.marzoftBackend||window.MarzoftSupabase||window.marzoftSupabase||{};const client=facade.client||window.supabaseClient||(facade.auth&&typeof facade.from==="function"?facade:null)||(window.supabase?.auth&&typeof window.supabase.from==="function"?window.supabase:null);return{facade:facade,
client:client}};const unwrapAuthResult=result=>{if(result?.error)throw result.error;const data=result?.data||result||{};return{session:data.session||null,user:data.user||data.session?.user||null}};const getAuthenticatedUser=async(client,initialUser)=>{if(initialUser)return initialUser
;if(!client?.auth?.getUser)return null;const result=await client.auth.getUser();if(result?.error)throw result.error;return result?.data?.user||null};const waitForRedirectUser=async client=>{for(let attempt=0;attempt<8;attempt+=1){const sessionResult=await client.auth.getSession()
;if(sessionResult?.error&&attempt===7)throw sessionResult.error;const user=sessionResult?.data?.session?.user||null;if(user)return user;await new Promise(resolve=>window.setTimeout(resolve,180+attempt*45))}return null};const requestPayload=user=>({client_id:user.id,project_type:draft.projectType,
goals:draft.goals,description:draft.story,budget:draft.budget,name:draft.name,email:draft.email,whatsapp:draft.whatsapp,status:"new"});const sendProjectRequest=async user=>{if(authEntry!=="project"||!hasProjectDraft()){try{sessionStorage.removeItem(intentKey)}catch(error){}
window.location.href="client-dashboard.html";return}const{facade:facade,client:client}=resolveBackend();const payload=requestPayload(user);if(typeof facade.saveProjectRequest==="function"){const result=await facade.saveProjectRequest(payload,user);if(result?.error)throw result.error}else if(client?.from){
const result=await client.from("project_requests").insert(payload);if(result?.error)throw result.error}else{throw new Error("We could not send that just now. Please try again or message us on WhatsApp.")}clearDraft();try{sessionStorage.removeItem(intentKey)}catch(error){}setStatus("","success",false)
;showPanel("success")};googleButton?.addEventListener("click",async()=>{setStatus("","error",false);if(authEntry==="project")writeDraft();const{facade:facade,client:client}=resolveBackend();const redirect=new URL(window.location.href);redirect.searchParams.set("project_auth","google")
;redirect.searchParams.set("project_intent",authEntry);redirect.hash="booking";rememberAuthIntent(authEntry);setLoading(true);try{let result;if(typeof facade.signInWithGoogle==="function"){result=await facade.signInWithGoogle({redirectTo:redirect.toString()})}else if(client?.auth?.signInWithOAuth){
result=await client.auth.signInWithOAuth({provider:"google",options:{redirectTo:redirect.toString()}})}else{throw new Error("Google sign-in is temporarily unavailable. Please continue with email.")}if(result?.error)throw result.error}catch(error){setLoading(false)
;setStatus(error?.message||"Google sign-in could not start. Please try again.")}});authForm?.addEventListener("submit",async event=>{event.preventDefault();if(!authForm.reportValidity())return;setStatus("","error",false);setLoading(true);if(authEntry==="project"){draft.email=authEmail.value.trim()
;writeDraft()}const credentials={email:authEmail.value.trim(),password:authPassword.value,metadata:{full_name:draft.name||""},redirectTo:(()=>{const redirect=new URL(window.location.href);redirect.searchParams.set("project_auth","email");redirect.searchParams.set("project_intent",authEntry)
;redirect.hash="booking";return redirect.toString()})()};rememberAuthIntent(authEntry);try{const{facade:facade,client:client}=resolveBackend();let result;if(authMode==="signup"){if(typeof facade.signUpWithEmail==="function"){result=await facade.signUpWithEmail(credentials)}else if(client?.auth?.signUp){
result=await client.auth.signUp({email:credentials.email,password:credentials.password,options:{data:credentials.metadata,emailRedirectTo:credentials.redirectTo}})}else{throw new Error("Email sign-up is temporarily unavailable. Please try again shortly.")}}else if(typeof facade.signInWithEmail==="function"){
result=await facade.signInWithEmail(credentials)}else if(client?.auth?.signInWithPassword){result=await client.auth.signInWithPassword({email:credentials.email,password:credentials.password})}else{throw new Error("Email sign-in is temporarily unavailable. Please try again shortly.")}
const auth=unwrapAuthResult(result);if(authMode==="signup"&&!auth.session){setStatus("Check your inbox to confirm your email. Your project brief is saved here and will be ready when you sign in.","success",false);return}const user=await getAuthenticatedUser(client,auth.user)
;if(!user)throw new Error("We could not confirm your account. Please sign in again.");await sendProjectRequest(user)}catch(error){setStatus(error?.message||"We could not complete that step. Please try again.")}finally{setLoading(false)}});const resumeAuth=async()=>{const url=new URL(window.location.href)
;const authProvider=url.searchParams.get("project_auth");if(!authProvider)return;const requestedIntent=url.searchParams.get("project_intent")||readAuthIntent();authEntry=requestedIntent==="project"?"project":"login";setAuthMode("signin");showPanel("auth");setLoading(true)
;setStatus("Finishing your secure sign-in…","success",false);try{const{client:client}=resolveBackend();if(!client?.auth)throw new Error("We could not finish your sign-in. Please try again shortly.");const user=await waitForRedirectUser(client);if(!user)throw new Error("Secure sign-in did not finish. Please try again.")
;url.searchParams.delete("project_auth");url.searchParams.delete("project_intent");try{history.replaceState({},"",url.toString())}catch(error){}await sendProjectRequest(user)}catch(error){const providerName=authProvider==="google"?"Google sign-in":"Email confirmation"
;setStatus(error?.message||`${providerName} could not be completed. Please try again.`,"error",false)}finally{setLoading(false)}};restoreDraftToForm();setAuthMode("signup");resumeAuth()})();(()=>{const header=document.getElementById("siteHeader");const hero=document.getElementById("home")
;const drawer=document.getElementById("mobileDrawer");const toggle=document.getElementById("menuToggle");if(!header||!hero)return;const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const internalLinks=Array.from(header.querySelectorAll('.nav-links a[href^="#"]'))
;const coarsePointer=window.matchMedia("(pointer: coarse)").matches;let heroEnd=0;let lastScrollY=window.scrollY;let lastPointerY=null;let lastDirection="down";let temporaryRevealTimer=0;let pointerTravel=0;let lastPointerTime=0;let upwardTravel=0;let upwardWheelTicks=0;let lastWheelTick=0;const updateBoundary=()=>{
heroEnd=hero.offsetTop+hero.offsetHeight-Math.max(12,header.offsetHeight*.35)};const isPastHero=()=>window.scrollY>heroEnd
;const isPinnedOpen=()=>drawer?.classList.contains("active")||document.body.classList.contains("auth-portal-open")||document.body.classList.contains("review-modal-open")||document.body.classList.contains("whatsapp-composer-open")||header.matches(":hover")||header.contains(document.activeElement);const resetRecallIntent=()=>{upwardTravel=0
;upwardWheelTicks=0};const showNavigation=(temporary=false)=>{window.clearTimeout(temporaryRevealTimer);header.classList.remove("nav-hidden");document.body.classList.remove("nav-is-hidden");if(temporary&&isPastHero()&&!isPinnedOpen()){temporaryRevealTimer=window.setTimeout(()=>{
if(isPastHero()&&!isPinnedOpen()&&lastDirection!=="up")hideNavigation()},1650)}};const hideNavigation=()=>{window.clearTimeout(temporaryRevealTimer);if(!isPastHero()||isPinnedOpen())return;header.classList.add("nav-hidden");document.body.classList.add("nav-is-hidden")};const updateCurrentLink=()=>{const marker=window.innerHeight*.42
;let currentId="";internalLinks.forEach(link=>{const section=document.querySelector(link.getAttribute("href"));if(section&&section.getBoundingClientRect().top<=marker)currentId=section.id});internalLinks.forEach(link=>{const active=link.getAttribute("href")===`#${currentId}`;link.classList.toggle("is-current",active)
;if(active)link.setAttribute("aria-current","location");else link.removeAttribute("aria-current")})};const onScroll=()=>{const currentY=window.scrollY;const delta=currentY-lastScrollY;const pastHero=isPastHero();header.classList.toggle("is-past-hero",pastHero);header.classList.remove("is-past-second");if(!pastHero){
lastDirection=delta<0?"up":"down";resetRecallIntent();showNavigation()}else if(delta>4){lastDirection="down";resetRecallIntent();hideNavigation()}else if(delta<-4){lastDirection="up";upwardTravel+=Math.abs(delta);if(upwardTravel>=110||upwardWheelTicks>=3)showNavigation()}lastScrollY=currentY;updateCurrentLink()}
;window.addEventListener("wheel",event=>{if(!isPastHero())return;const now=performance.now();if(event.deltaY<-5){if(now-lastWheelTick>620)upwardWheelTicks=0;upwardWheelTicks+=1;lastWheelTick=now;lastDirection="up";if(upwardWheelTicks>=3)showNavigation()}else if(event.deltaY>5){resetRecallIntent()}},{passive:true});if(!coarsePointer){
document.addEventListener("pointermove",event=>{const now=performance.now();if(now-lastPointerTime>180)pointerTravel=0;const pointerDelta=lastPointerY===null?0:lastPointerY-event.clientY;if(pointerDelta>0)pointerTravel+=pointerDelta;else if(pointerDelta<-1)pointerTravel=0;lastPointerTime=now;if(!isPastHero()){lastPointerY=event.clientY
;pointerTravel=0;return}if(event.clientY<=78){lastDirection="pointer";pointerTravel=0;showNavigation()}else if(pointerTravel>18){lastDirection="pointer";pointerTravel=0;showNavigation(true)}lastPointerY=event.clientY},{passive:true});header.addEventListener("pointerenter",()=>showNavigation());header.addEventListener("pointerleave",()=>{
if(isPastHero()&&lastDirection!=="up")temporaryRevealTimer=window.setTimeout(hideNavigation,900)})}header.addEventListener("focusin",()=>showNavigation());header.addEventListener("focusout",()=>{if(isPastHero())temporaryRevealTimer=window.setTimeout(hideNavigation,950)});const closeMobileDrawer=()=>{drawer?.classList.remove("active")
;drawer?.setAttribute("aria-hidden","true");toggle?.setAttribute("aria-expanded","false");toggle?.setAttribute("aria-label","Open Navigation Menu");document.body.classList.remove("nav-menu-open")};document.querySelectorAll("[data-nav-project]").forEach(trigger=>{trigger.addEventListener("click",event=>{event.preventDefault()
;closeMobileDrawer();window.dispatchEvent(new CustomEvent("marzoft:close-auth-portal"));showNavigation();const booking=document.getElementById("booking");booking?.scrollIntoView({behavior:reducedMotion?"auto":"smooth",block:"center"});window.setTimeout(()=>document.querySelector("[data-project-open]")?.click(),reducedMotion?0:620)})})
;window.addEventListener("marzoft:navigation-state",()=>{if(isPinnedOpen())showNavigation();else if(isPastHero()&&lastDirection!=="up")hideNavigation();else onScroll()});window.addEventListener("scroll",onScroll,{passive:true});window.addEventListener("resize",()=>{updateBoundary();onScroll()},{passive:true})
;window.addEventListener("load",()=>{updateBoundary();onScroll()},{once:true});if("ResizeObserver"in window)new ResizeObserver(updateBoundary).observe(hero);updateBoundary();onScroll()})();(()=>{const header=document.getElementById("siteHeader");const logo=document.getElementById("pastNavLogo")
;const toggle=document.getElementById("menuToggle");const drawer=document.getElementById("mobileDrawer");const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(!header||!toggle||!drawer)return;let lastY=window.scrollY;let menuOpen=false;let tapCount=0;let tapTimer=0;let typedWord="";let secretWord="adminx"
;const closeMenu=()=>{menuOpen=false;drawer.classList.remove("active");drawer.setAttribute("aria-hidden","true");toggle.setAttribute("aria-expanded","false");toggle.setAttribute("aria-label","Open Navigation Menu");document.body.classList.remove("nav-menu-open")};const openMenu=()=>{menuOpen=true;header.classList.remove("nav-hidden")
;drawer.classList.add("active");drawer.setAttribute("aria-hidden","false");toggle.setAttribute("aria-expanded","true");toggle.setAttribute("aria-label","Close Navigation Menu");document.body.classList.add("nav-menu-open")};toggle.addEventListener("click",()=>{menuOpen?closeMenu():openMenu()})
;drawer.querySelectorAll('a[href^="#"], [data-nav-project]').forEach(link=>link.addEventListener("click",()=>closeMenu()));document.querySelectorAll('.past-nav-header a[href^="#"]').forEach(link=>{if(link===logo)return;link.addEventListener("click",event=>{const target=document.querySelector(link.getAttribute("href"));if(!target)return
;event.preventDefault();closeMenu();target.scrollIntoView({behavior:reducedMotion?"auto":"smooth",block:"start"})})});const openAdmin=()=>{window.location.href="adminlogin.html"};logo?.addEventListener("click",event=>{event.preventDefault();tapCount+=1;window.clearTimeout(tapTimer);if(tapCount>=3){tapCount=0;openAdmin();return}
tapTimer=window.setTimeout(()=>{if(tapCount<3)document.getElementById("home")?.scrollIntoView({behavior:reducedMotion?"auto":"smooth"});tapCount=0},400)});document.addEventListener("keydown",event=>{if(event.key.length!==1||/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName||""))return
;typedWord=`${typedWord}${event.key.toLowerCase()}`.slice(-secretWord.length);if(typedWord===secretWord)openAdmin()});(async()=>{try{const api=window.marzoftBackend||window.MarzoftSupabase||window.AdminAPI;const config=typeof api?.getConfig==="function"?await api.getConfig():null
;const supplied=config?.security?.secretWord||config?.settings?.secretWord;if(typeof supplied==="string"&&supplied.trim())secretWord=supplied.trim().toLowerCase()}catch(_){}})();const onScroll=()=>{const currentY=window.scrollY;if(!menuOpen){
if(currentY<=100||currentY<lastY-2)header.classList.remove("nav-hidden");else if(currentY>lastY+2)header.classList.add("nav-hidden")}lastY=currentY};window.addEventListener("scroll",onScroll,{passive:true});window.addEventListener("marzoft:navigation-state",()=>{if(menuOpen)header.classList.remove("nav-hidden")});onScroll()})();(()=>{
const portal=document.getElementById("authPortal");const form=document.getElementById("portalAuthForm");const emailInput=document.getElementById("portalAuthEmail");const passwordInput=document.getElementById("portalAuthPassword");const passwordToggle=document.getElementById("portalPasswordToggle")
;const submitButton=document.getElementById("portalAuthSubmit");const googleButton=document.getElementById("portalGoogleAuth");const status=document.getElementById("portalAuthStatus");const title=document.getElementById("authPortalTitle");const description=document.getElementById("authPortalDescription")
;const tabs=Array.from(document.querySelectorAll("[data-portal-auth-mode]"));if(!portal||!form||!emailInput||!passwordInput||!submitButton||!googleButton)return;let authMode="signin";let lastFocusedElement=null;let loading=false;let requestVersion=0;let portalFocusTimer=0
;const portalBackground=[document.getElementById("siteHeader"),document.querySelector("main"),document.querySelector(".site-footer"),document.getElementById("mobileDrawer")].filter(Boolean);const resolveBackend=()=>{const facade=window.marzoftBackend||window.MarzoftSupabase||window.marzoftSupabase||{}
;const client=facade.client||window.supabaseClient||(facade.auth&&typeof facade.from==="function"?facade:null)||(window.supabase?.auth&&typeof window.supabase.from==="function"?window.supabase:null);return{facade:facade,client:client}};const setStatus=(message="",kind="error")=>{status.textContent=message
;status.classList.toggle("has-message",Boolean(message));status.classList.toggle("is-success",kind==="success")};const setLoading=isLoading=>{loading=isLoading;portal.classList.toggle("is-loading",isLoading);portal.setAttribute("aria-busy",String(isLoading));submitButton.disabled=isLoading;googleButton.disabled=isLoading
;tabs.forEach(tab=>{tab.disabled=isLoading})};const setMode=mode=>{authMode=mode==="signup"?"signup":"signin";const signingUp=authMode==="signup";tabs.forEach(tab=>{const active=tab.dataset.portalAuthMode===authMode;tab.classList.toggle("is-active",active);tab.setAttribute("aria-pressed",String(active))})
;title.textContent=signingUp?"Let’s make it official.":"Good to see you.";description.textContent=signingUp?"Create one secure account to send requests and follow every project update.":"Sign in to follow your project from first brief to final launch.";passwordInput.autocomplete=signingUp?"new-password":"current-password"
;passwordInput.minLength=signingUp?8:6;passwordInput.placeholder=signingUp?"Create at least 8 characters":"Your password";submitButton.innerHTML=signingUp?"Create my account <span>→</span>":"Enter my dashboard <span>→</span>";setStatus()};const openPortal=(mode="signin",restoreFocus=true)=>{
if(restoreFocus&&document.activeElement instanceof HTMLElement){lastFocusedElement=document.activeElement.closest("#mobileDrawer")?document.getElementById("menuToggle"):document.activeElement}const drawer=document.getElementById("mobileDrawer");const toggle=document.getElementById("menuToggle");drawer?.classList.remove("active")
;drawer?.setAttribute("aria-hidden","true");toggle?.setAttribute("aria-expanded","false");toggle?.setAttribute("aria-label","Open Navigation Menu");document.body.classList.remove("nav-menu-open");setMode(mode);portalBackground.forEach(region=>{region.inert=true});portal.inert=false;portal.classList.add("is-open")
;portal.setAttribute("aria-hidden","false");document.body.classList.add("auth-portal-open");window.dispatchEvent(new CustomEvent("marzoft:navigation-state"));window.clearTimeout(portalFocusTimer);portalFocusTimer=window.setTimeout(()=>{const compact=window.matchMedia("(max-width:820px)").matches;emailInput.focus({preventScroll:!compact})
;if(compact)emailInput.scrollIntoView({block:"center",behavior:"auto"})},320)};const closePortal=(restoreFocus=true)=>{window.clearTimeout(portalFocusTimer);requestVersion+=1;setLoading(false);const focusTarget=restoreFocus?lastFocusedElement||document.querySelector("[data-auth-portal-open]"):document.querySelector("[data-project-open]")
;portalBackground.forEach(region=>{region.inert=false});focusTarget?.focus?.({preventScroll:true});portal.classList.remove("is-open");portal.setAttribute("aria-hidden","true");portal.inert=true;document.body.classList.remove("auth-portal-open");passwordInput.value="";passwordInput.type="password";passwordToggle.textContent="Show"
;passwordToggle.setAttribute("aria-label","Show password");setStatus();window.dispatchEvent(new CustomEvent("marzoft:navigation-state"))};document.querySelectorAll("[data-auth-portal-open]").forEach(trigger=>{trigger.addEventListener("click",event=>{event.preventDefault();openPortal("signin")})})
;document.querySelectorAll("[data-auth-portal-close]").forEach(trigger=>trigger.addEventListener("click",()=>closePortal()));window.addEventListener("marzoft:close-auth-portal",()=>closePortal(false));tabs.forEach(tab=>tab.addEventListener("click",()=>setMode(tab.dataset.portalAuthMode)));passwordToggle.addEventListener("click",()=>{
const reveal=passwordInput.type==="password";passwordInput.type=reveal?"text":"password";passwordToggle.textContent=reveal?"Hide":"Show";passwordToggle.setAttribute("aria-label",reveal?"Hide password":"Show password");passwordInput.focus({preventScroll:true})});portal.addEventListener("keydown",event=>{if(event.key==="Escape"){
event.preventDefault();closePortal();return}if(event.key!=="Tab")return;const focusable=Array.from(portal.querySelectorAll("button:not([disabled]):not(.auth-portal-backdrop),input:not([disabled]),a[href]")).filter(element=>element.getClientRects().length>0);if(!focusable.length)return;const first=focusable[0]
;const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});const unwrapAuthResult=result=>{if(result?.error)throw result.error;const data=result?.data||result||{};return{
session:data.session||null,user:data.user||data.session?.user||null}};const getUser=async(client,initialUser)=>{if(initialUser)return initialUser;if(!client?.auth?.getUser)return null;const result=await client.auth.getUser();if(result?.error)throw result.error;return result?.data?.user||null};const waitForRedirectUser=async client=>{
for(let attempt=0;attempt<8;attempt+=1){const result=await client.auth.getSession();if(result?.error&&attempt===7)throw result.error;const user=result?.data?.session?.user||null;if(user)return user;await new Promise(resolve=>window.setTimeout(resolve,180+attempt*45))}return null};const dashboard=()=>{
window.location.href="client-dashboard.html"};const authRedirectUrl=provider=>{const url=new URL(window.location.href);url.searchParams.set("portal_auth",provider);url.hash="client-login";return url.toString()};googleButton.addEventListener("click",async()=>{setStatus();const requestId=++requestVersion;setLoading(true);try{
const{facade:facade,client:client}=resolveBackend();const redirectTo=authRedirectUrl("google");let result;if(typeof facade.signInWithGoogle==="function"){result=await facade.signInWithGoogle({redirectTo:redirectTo})}else if(client?.auth?.signInWithOAuth){result=await client.auth.signInWithOAuth({provider:"google",options:{
redirectTo:redirectTo}})}else{throw new Error("Google sign-in is temporarily unavailable. Please continue with email.")}if(result?.error)throw result.error;if(requestId!==requestVersion)return;const auth=unwrapAuthResult(result);if(auth.user||auth.session?.user)dashboard()}catch(error){if(requestId!==requestVersion)return
;setLoading(false);setStatus(error?.message||"Google sign-in could not start. Please try again.")}});form.addEventListener("submit",async event=>{event.preventDefault();if(!form.reportValidity())return;setStatus();const requestId=++requestVersion;setLoading(true);const credentials={email:emailInput.value.trim(),
password:passwordInput.value,redirectTo:authRedirectUrl("email")};try{const{facade:facade,client:client}=resolveBackend();let result;if(authMode==="signup"){if(typeof facade.signUpWithEmail==="function"){result=await facade.signUpWithEmail(credentials)}else if(client?.auth?.signUp){result=await client.auth.signUp({email:credentials.email,
password:credentials.password,options:{emailRedirectTo:credentials.redirectTo}})}else{throw new Error("Email sign-up is temporarily unavailable. Please try again shortly.")}}else if(typeof facade.signInWithEmail==="function"){result=await facade.signInWithEmail(credentials)}else if(client?.auth?.signInWithPassword){
result=await client.auth.signInWithPassword({email:credentials.email,password:credentials.password})}else{throw new Error("Email sign-in is temporarily unavailable. Please try again shortly.")}const auth=unwrapAuthResult(result);if(requestId!==requestVersion)return;if(authMode==="signup"&&!auth.session){
setStatus("Your account is almost ready. Check your inbox and confirm your email to enter the dashboard.","success");return}const user=await getUser(client,auth.user);if(!user)throw new Error("We could not confirm your account. Please sign in once more.");dashboard()}catch(error){if(requestId!==requestVersion)return
;setStatus(error?.message||"We could not complete that step. Please try again.")}finally{if(requestId===requestVersion)setLoading(false)}});const resumePortalAuth=async()=>{const url=new URL(window.location.href);const provider=url.searchParams.get("portal_auth");if(!provider)return;openPortal("signin",false)
;const requestId=++requestVersion;setLoading(true);setStatus("Finishing your secure sign-in…","success");try{const{client:client}=resolveBackend();if(!client?.auth)throw new Error("We could not finish your sign-in. Please try again shortly.");const user=await waitForRedirectUser(client);if(requestId!==requestVersion)return
;if(!user)throw new Error("Secure sign-in did not finish. Please try again.");url.searchParams.delete("portal_auth");try{history.replaceState({},"",url.toString())}catch(error){}dashboard()}catch(error){if(requestId!==requestVersion)return;setStatus(error?.message||"Secure sign-in could not be completed. Please try again.")}finally{
if(requestId===requestVersion)setLoading(false)}};setMode("signin");portal.inert=true;resumePortalAuth()})();(()=>{const modal=document.getElementById("reviewModal");const form=document.getElementById("reviewForm");const track=document.getElementById("reviewsTrack");const viewport=document.getElementById("reviewsViewport")
;const count=document.getElementById("reviewsCount");const position=document.getElementById("reviewPosition");const progress=document.getElementById("reviewsProgress");const section=document.getElementById("reviews");const previous=document.querySelector("[data-review-prev]");const next=document.querySelector("[data-review-next]")
;const submit=document.getElementById("reviewSubmit");const status=document.getElementById("reviewStatus");const nameInput=document.getElementById("reviewName");const businessInput=document.getElementById("reviewBusiness");const projectTypeInput=document.getElementById("reviewProjectType")
;const quoteInput=document.getElementById("reviewQuote");const quoteCount=document.getElementById("reviewQuoteCount");const ratingInputs=Array.from(document.querySelectorAll('input[name="rating"]'));if(!modal||!form||!track||!viewport||!previous||!next||!submit)return
;const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const localKey="marzoft_review_preview_v1";const background=[document.getElementById("siteHeader"),document.querySelector("main"),document.querySelector(".site-footer"),document.getElementById("mobileDrawer"),document.querySelector(".whatsapp-floating-cta")].filter(Boolean);let reviews=[];let localReviews=[]
;let lastFocusedElement=null;let closeTimer=0;let loading=false;let realtimeChannel=null;const resolveBackend=()=>{const facade=window.marzoftBackend||window.MarzoftSupabase||window.marzoftSupabase||{}
;const client=facade.client||window.supabaseClient||(facade.auth&&typeof facade.from==="function"?facade:null)||(window.supabase?.auth&&typeof window.supabase.from==="function"?window.supabase:null);return{facade:facade,client:client}};const safeText=(value,fallback="")=>String(value??fallback).trim()
;const reviewIdentity=review=>safeText(review.quote?`${review.name}|${review.quote}`:review.id||review.client_request_id).toLowerCase();const normalizeReview=(row={},index=0)=>{const rating=Math.max(1,Math.min(5,Number(row.rating)||5));return{
id:safeText(row.id||row.client_request_id||`review-${Date.now()}-${index}`),name:safeText(row.name||row.reviewer_name,"Marzoft client").slice(0,70),business:safeText(row.business||row.company).slice(0,90),projectType:safeText(row.project_type||row.projectType).slice(0,90),rating:rating,
quote:safeText(row.review_text||row.review||row.quote||row.content||row.text).slice(0,500),createdAt:row.created_at||row.createdAt||(new Date).toISOString(),localOnly:Boolean(row.localOnly)}};const readLocalReviews=()=>{try{const parsed=JSON.parse(localStorage.getItem(localKey)||"[]")
;return Array.isArray(parsed)?parsed.map(normalizeReview).filter(item=>item.quote):[]}catch(error){return[]}};const writeLocalReviews=()=>{try{localStorage.setItem(localKey,JSON.stringify(localReviews.slice(0,30)))}catch(error){}};const mergeReviews=(...collections)=>{const seen=new Set
;return collections.flat().map(normalizeReview).filter(item=>{if(!item.quote)return false;const identity=reviewIdentity(item);if(seen.has(identity))return false;seen.add(identity);return true}).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))};const element=(tag,className,text)=>{
const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};const makeEmptyCard=()=>{const card=element("article","review-card review-empty-card");card.setAttribute("role","status")
;card.append(element("span","past-review-quote-mark","“"));card.append(element("h3","","The next kind words could be yours."));card.append(element("p","","Build something memorable with Marzoft."));return card};const makeReviewCard=(review,index,total)=>{
const card=element("article","review-card past-testimonial-card");card.setAttribute("role","group");card.setAttribute("aria-roledescription","slide");card.setAttribute("aria-label",`${review.name}'s review, ${index+1} of ${total}`);card.dataset.reviewId=review.id;const glare=element("span","glass-glare")
;glare.setAttribute("aria-hidden","true");const top=element("div","review-card-top");const stars=element("span","review-rating","★".repeat(review.rating));stars.setAttribute("aria-label",`${review.rating} out of 5 stars`);const number=element("span","review-number","CLIENT NOTE");top.append(stars,number)
;const quote=element("blockquote","",`“${review.quote}”`);const person=element("div","review-card-person");const avatar=element("span","review-avatar",(review.name||"M").charAt(0).toUpperCase());const personCopy=element("div","review-person-copy")
;const detail=[review.business,review.projectType].filter(Boolean).join(" · ")||"Marzoft client";personCopy.append(element("strong","",review.name),element("span","",detail));person.append(avatar,personCopy);card.append(glare,top,quote,person);if(!reducedMotion){card.addEventListener("pointermove",event=>{
if(!card.classList.contains("is-active")||event.pointerType==="touch")return;const rect=card.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width-.5;const y=(event.clientY-rect.top)/rect.height-.5;card.style.setProperty("--review-tilt-y",`${(x*3.2).toFixed(2)}deg`)
;card.style.setProperty("--review-tilt-x",`${(y*-3.2).toFixed(2)}deg`);glare.style.opacity="1";glare.style.setProperty("--glare-x",`${((x+.5)*100).toFixed(0)}%`);glare.style.setProperty("--glare-y",`${((y+.5)*100).toFixed(0)}%`)});card.addEventListener("pointerleave",()=>{
card.style.setProperty("--review-tilt-y","0deg");card.style.setProperty("--review-tilt-x","0deg");glare.style.opacity="0"})}return card};const visibleCardIndex=()=>{const cards=Array.from(track.querySelectorAll(".review-card:not(.review-empty-card)"));if(!cards.length)return 0
;const viewportCenter=viewport.scrollLeft+viewport.clientWidth/2;let closest=0;let distance=Infinity;cards.forEach((card,index)=>{const cardCenter=card.offsetLeft+card.offsetWidth/2;const nextDistance=Math.abs(cardCenter-viewportCenter);if(nextDistance<distance){distance=nextDistance;closest=index}})
;return closest};const syncCarouselGeometry=()=>{const card=track.querySelector(".review-card");const sidePad=card?Math.max(12,(viewport.clientWidth-card.offsetWidth)/2):24;viewport.style.setProperty("--review-side-pad",`${sidePad}px`)};const updateCarouselState=()=>{const total=reviews.length
;const maxLeft=Math.max(0,viewport.scrollWidth-viewport.clientWidth-2);const currentIndex=total?visibleCardIndex():0;const current=total?currentIndex+1:0;const cards=Array.from(track.querySelectorAll(".review-card:not(.review-empty-card)"))
;cards.forEach((card,index)=>card.classList.toggle("is-active",index===currentIndex));count.textContent=!total?"Ready for your story":total===1?"1 client story":`${total} client stories`;position.textContent=total?`Review ${current} of ${total}`:"No reviews yet"
;if(progress)progress.style.width=total?`${current/total*100}%`:"0%";previous.disabled=!total||viewport.scrollLeft<=3;next.disabled=!total||viewport.scrollLeft>=maxLeft};const renderReviews=(focusId="")=>{track.replaceChildren()
;if(!reviews.length)track.append(makeEmptyCard());else reviews.forEach((review,index)=>track.append(makeReviewCard(review,index,reviews.length)));requestAnimationFrame(()=>{syncCarouselGeometry();updateCarouselState();if(focusId){
const card=Array.from(track.querySelectorAll("[data-review-id]")).find(item=>item.dataset.reviewId===String(focusId));card?.classList.add("is-new");card?.scrollIntoView({behavior:reducedMotion?"auto":"smooth",block:"nearest",inline:"center"});window.setTimeout(()=>card?.classList.remove("is-new"),reducedMotion?0:1200)}})}
;const loadRemoteReviews=async()=>{const{facade:facade,client:client}=resolveBackend();let result=null;if(typeof facade.listReviews==="function")result=await facade.listReviews();else if(typeof facade.loadReviews==="function")result=await facade.loadReviews();else if(typeof facade.getReviews==="function")result=await facade.getReviews();else if(client?.from)result=await client.from("reviews").select("*").order("created_at",{
ascending:false}).limit(50);else return[];if(result?.error)throw result.error;const rows=result?.data||result?.reviews||result||[];return Array.isArray(rows)?rows:[]};const saveRemoteReview=async payload=>{const{facade:facade,client:client}=resolveBackend();let result=null
;if(typeof facade.addReview==="function")result=await facade.addReview(payload);else if(typeof facade.saveReview==="function")result=await facade.saveReview(payload);else if(typeof facade.createReview==="function")result=await facade.createReview(payload);else if(client?.from)result=await client.from("reviews").insert(payload).select().single();else return null
;if(result?.error)throw result.error;return result?.data||result?.review||result||null};const startRealtimeReviews=()=>{const{client:client}=resolveBackend();if(!client?.channel||realtimeChannel)return;try{realtimeChannel=client.channel("marzoft-client-stories").on("postgres_changes",{event:"INSERT",schema:"public",table:"reviews"
},change=>{const incoming=normalizeReview(change?.new||{});if(!incoming.quote)return;reviews=mergeReviews([incoming],reviews,localReviews);renderReviews(incoming.id)}).subscribe()}catch(error){realtimeChannel=null}};const setStatus=(message="",kind="")=>{status.textContent=message
;status.className=`review-submit-status${kind?` is-${kind}`:""}`};const setLoading=value=>{loading=value;modal.classList.toggle("is-loading",value);modal.setAttribute("aria-busy",String(value));submit.disabled=value};const closeMobileDrawer=()=>{const drawer=document.getElementById("mobileDrawer")
;const toggle=document.getElementById("menuToggle");drawer?.classList.remove("active");drawer?.setAttribute("aria-hidden","true");toggle?.setAttribute("aria-expanded","false");toggle?.setAttribute("aria-label","Open Navigation Menu");document.body.classList.remove("nav-menu-open")};const openModal=trigger=>{window.clearTimeout(closeTimer)
;lastFocusedElement=trigger?.closest?.("#mobileDrawer")?document.getElementById("menuToggle"):trigger||document.activeElement;closeMobileDrawer();window.dispatchEvent(new CustomEvent("marzoft:close-auth-portal"));window.dispatchEvent(new CustomEvent("marzoft:close-whatsapp-composer"));background.forEach(region=>{region.inert=true})
;modal.inert=false;modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");document.body.classList.add("review-modal-open");window.dispatchEvent(new CustomEvent("marzoft:navigation-state"));window.setTimeout(()=>nameInput.focus({preventScroll:true}),reducedMotion?0:300)};const closeModal=(restoreFocus=true)=>{
window.clearTimeout(closeTimer);setLoading(false);const target=restoreFocus?lastFocusedElement:null;background.forEach(region=>{region.inert=false});target?.focus?.({preventScroll:true});modal.classList.remove("is-open");modal.setAttribute("aria-hidden","true");modal.inert=true;document.body.classList.remove("review-modal-open")
;setStatus();window.dispatchEvent(new CustomEvent("marzoft:navigation-state"))};document.addEventListener("click",event=>{const openTrigger=event.target.closest("[data-review-open]");if(openTrigger){event.preventDefault();openModal(openTrigger);return}if(event.target.closest("[data-review-close]"))closeModal()})
;modal.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();closeModal();return}if(event.key!=="Tab")return;const focusable=Array.from(modal.querySelectorAll("button:not([disabled]):not(.review-modal-backdrop),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]")).filter(node=>node.getClientRects().length);if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1]
;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});ratingInputs.forEach((input,inputIndex)=>input.addEventListener("change",()=>{
ratingInputs.forEach((item,index)=>item.nextElementSibling?.classList.toggle("is-selected",index<=inputIndex))}));const syncSelectedRating=()=>{const selectedIndex=ratingInputs.findIndex(input=>input.checked);ratingInputs.forEach((item,index)=>item.nextElementSibling?.classList.toggle("is-selected",index<=selectedIndex))}
;const updateQuoteCount=()=>{if(quoteCount)quoteCount.textContent=`${quoteInput.value.length}/500`};quoteInput.addEventListener("input",updateQuoteCount);const moveCarousel=direction=>{const card=track.querySelector(".review-card:not(.review-empty-card)");const gap=parseFloat(getComputedStyle(track).gap)||16
;const distance=card?card.getBoundingClientRect().width+gap:viewport.clientWidth*.85;viewport.scrollBy({left:direction*distance,behavior:reducedMotion?"auto":"smooth"})};previous.addEventListener("click",()=>moveCarousel(-1));next.addEventListener("click",()=>moveCarousel(1));viewport.addEventListener("keydown",event=>{
if(event.key==="ArrowLeft"){event.preventDefault();moveCarousel(-1)}if(event.key==="ArrowRight"){event.preventDefault();moveCarousel(1)}});let carouselFrame=0;viewport.addEventListener("scroll",()=>{cancelAnimationFrame(carouselFrame);carouselFrame=requestAnimationFrame(updateCarouselState)},{passive:true})
;if("ResizeObserver"in window)new ResizeObserver(()=>{syncCarouselGeometry();updateCarouselState()}).observe(viewport);form.addEventListener("submit",async event=>{event.preventDefault();if(!form.reportValidity()||loading)return;const selectedRating=form.querySelector('input[name="rating"]:checked');if(!selectedRating)return
;const clientRequestId=window.crypto?.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(16).slice(2)}`;const optimistic=normalizeReview({id:clientRequestId,client_request_id:clientRequestId,name:nameInput.value,business:businessInput.value,project_type:projectTypeInput.value,rating:Number(selectedRating.value),
review_text:quoteInput.value,created_at:(new Date).toISOString(),localOnly:true});reviews=mergeReviews([optimistic],reviews);renderReviews(optimistic.id);setLoading(true);setStatus("Your review is already in the gallery. Publishing it for everyone…","success");const payload={name:optimistic.name,business:optimistic.business||null,
project_type:optimistic.projectType||null,rating:optimistic.rating,review_text:optimistic.quote,created_at:optimistic.createdAt};try{const saved=await saveRemoteReview(payload);if(saved){const normalizedSaved=normalizeReview({...payload,...saved,localOnly:false})
;reviews=mergeReviews([normalizedSaved],reviews.filter(item=>item.id!==optimistic.id));localReviews=localReviews.filter(item=>item.id!==optimistic.id);writeLocalReviews();renderReviews(normalizedSaved.id);setStatus("Published—thank you for adding your voice.","success")}else{localReviews=mergeReviews([optimistic],localReviews)
;writeLocalReviews();setStatus("Your review is now visible here. Thank you for sharing it.","success")}form.reset();updateQuoteCount();syncSelectedRating();closeTimer=window.setTimeout(()=>{closeModal(false);document.getElementById("reviews")?.scrollIntoView({behavior:reducedMotion?"auto":"smooth",block:"center"})},reducedMotion?300:2100)
}catch(error){localReviews=mergeReviews([optimistic],localReviews);writeLocalReviews();setStatus("Your words are visible here, but we could not publish them for everyone yet. Please try again shortly.","error")}finally{setLoading(false)}});const initialiseReviews=async()=>{modal.inert=true;localReviews=readLocalReviews()
;reviews=mergeReviews(localReviews);renderReviews();try{const remoteReviews=await loadRemoteReviews();reviews=mergeReviews(remoteReviews,localReviews);renderReviews()}catch(error){count.textContent=reviews.length===1?"1 client story":reviews.length?`${reviews.length} client stories`:"Ready for your story"}finally{startRealtimeReviews()}}
;window.addEventListener("marzoft:close-review-modal",()=>closeModal(false));if("IntersectionObserver"in window&&section&&!reducedMotion){const sectionObserver=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting))return;section.classList.add("reviews-ready","past-reviews-ready")
;sectionObserver.disconnect()},{threshold:.14});sectionObserver.observe(section)}else{section?.classList.add("reviews-ready","past-reviews-ready")}syncSelectedRating();initialiseReviews();window.addEventListener("pagehide",()=>{const{client:client}=resolveBackend()
;if(realtimeChannel&&client?.removeChannel)client.removeChannel(realtimeChannel)},{once:true})})();(()=>{const modal=document.getElementById("whatsappComposer");const form=document.getElementById("whatsappComposerForm");const message=document.getElementById("whatsappMessage")
;const messageCount=document.getElementById("whatsappMessageCount");const sendButton=form?.querySelector(".whatsapp-send-button");const promptButtons=Array.from(document.querySelectorAll("[data-whatsapp-prompt]"));const floatingButton=document.querySelector(".whatsapp-floating-cta")
;if(!modal||!form||!message||!messageCount||!sendButton)return;const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const defaultPhone="919999999999"
;const background=[document.getElementById("siteHeader"),document.querySelector("main"),document.querySelector(".site-footer"),document.getElementById("mobileDrawer"),floatingButton].filter(Boolean);let currentPhone=defaultPhone;let lastFocusedElement=null;const updateMessageState=()=>{
const length=message.value.length;messageCount.textContent=`${length} of 700`;sendButton.disabled=!message.value.trim();promptButtons.forEach(button=>button.classList.toggle("is-selected",button.dataset.whatsappPrompt===message.value.trim()))};const closeMobileDrawer=()=>{
const drawer=document.getElementById("mobileDrawer");const toggle=document.getElementById("menuToggle");drawer?.classList.remove("active");drawer?.setAttribute("aria-hidden","true");toggle?.setAttribute("aria-expanded","false");toggle?.setAttribute("aria-label","Open Navigation Menu")
;document.body.classList.remove("nav-menu-open")};const extractWhatsAppDetails=trigger=>{const href=trigger?.closest?.("a[href]")?.getAttribute("href")||"";if(!/wa\.me\//i.test(href))return{phone:defaultPhone,text:trigger?.dataset?.whatsappMessage||""};try{const url=new URL(href,window.location.href)
;const phone=url.pathname.replace(/\D/g,"")||defaultPhone;return{phone:phone,text:url.searchParams.get("text")||""}}catch(error){return{phone:defaultPhone,text:""}}};const openComposer=trigger=>{const details=extractWhatsAppDetails(trigger);currentPhone=details.phone
;if(!message.value.trim()&&details.text)message.value=details.text;lastFocusedElement=trigger?.closest?.("#mobileDrawer")?document.getElementById("menuToggle"):trigger||document.activeElement;closeMobileDrawer();window.dispatchEvent(new CustomEvent("marzoft:close-auth-portal"))
;window.dispatchEvent(new CustomEvent("marzoft:close-review-modal"));background.forEach(region=>{region.inert=true});modal.inert=false;modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");document.body.classList.add("whatsapp-composer-open");updateMessageState()
;window.dispatchEvent(new CustomEvent("marzoft:navigation-state"));window.setTimeout(()=>message.focus({preventScroll:true}),reducedMotion?0:320)};const closeComposer=(restoreFocus=true)=>{const target=restoreFocus?lastFocusedElement:null;background.forEach(region=>{region.inert=false})
;modal.classList.remove("is-open");modal.setAttribute("aria-hidden","true");modal.inert=true;document.body.classList.remove("whatsapp-composer-open");target?.focus?.({preventScroll:true});window.dispatchEvent(new CustomEvent("marzoft:navigation-state"))};document.addEventListener("click",event=>{
const trigger=event.target.closest('[data-whatsapp-compose],a[href*="wa.me/"]');if(trigger&&!trigger.closest("#whatsappComposer")){event.preventDefault();openComposer(trigger);return}if(event.target.closest("[data-whatsapp-close]"))closeComposer()})
;promptButtons.forEach(button=>button.addEventListener("click",()=>{message.value=button.dataset.whatsappPrompt||"";updateMessageState();message.focus({preventScroll:true});message.setSelectionRange(message.value.length,message.value.length)}));message.addEventListener("input",updateMessageState)
;form.addEventListener("submit",event=>{event.preventDefault();const text=message.value.trim();if(!text){message.focus();return}const preparedMessage=/^hi\s+marzoft\b/i.test(text)?text:`Hi Marzoft — ${text}`
;const url=`https://wa.me/${currentPhone}?text=${encodeURIComponent(preparedMessage)}`;const link=document.createElement("a");link.href=url;link.target="_blank";link.rel="noopener noreferrer";document.body.append(link);link.click();link.remove();window.setTimeout(()=>closeComposer(false),reducedMotion?0:240)})
;modal.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();closeComposer();return}if(event.key!=="Tab")return;const focusable=Array.from(modal.querySelectorAll("button:not([disabled]):not(.whatsapp-composer-backdrop),textarea:not([disabled]),a[href]")).filter(node=>node.getClientRects().length)
;if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}})
;window.addEventListener("marzoft:close-whatsapp-composer",()=>closeComposer(false));modal.inert=true;updateMessageState()})();(()=>{const widget=document.getElementById("dd-chat-widget");const box=document.getElementById("dd-chat-box");const openButton=document.getElementById("dd-chat-open-btn")
;const closeButton=document.getElementById("dd-chat-close-btn");const messages=document.getElementById("dd-chat-messages");const input=document.getElementById("dd-chat-input");const send=document.getElementById("dd-chat-send-btn");if(!widget||!box||!openButton||!closeButton||!messages||!input||!send)return
;const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const defaultPhone="919999999999";let phone=defaultPhone;let greeted=false;let isOpen=false;const addMessage=(text,user=false)=>{const bubble=document.createElement("div");bubble.className=`past-wa-message${user?" user":""}`
;bubble.textContent=text;messages.append(bubble);messages.scrollTop=messages.scrollHeight};const updateSend=()=>{const text=input.value.trim();send.classList.toggle("is-disabled",!text)
;send.href=text?`https://wa.me/${phone}?text=${encodeURIComponent(/^hi\s+marzoft\b/i.test(text)?text:`Hi Marzoft — ${text}`)}`:"#"};const greet=()=>{if(greeted)return;greeted=true
;const notes=["Hi! I’m the Marzoft team’s digital concierge.","Tell us what you’re planning — we’ll point you in the right direction."];notes.forEach((note,index)=>window.setTimeout(()=>addMessage(note),reducedMotion?0:420+index*610))};const open=(prefill="")=>{
if(prefill&&!input.value.trim())input.value=prefill;isOpen=true;box.classList.add("is-open");box.setAttribute("aria-hidden","false");greet();updateSend();window.setTimeout(()=>input.focus({preventScroll:true}),reducedMotion?0:220)};const close=()=>{isOpen=false;box.classList.remove("is-open")
;box.setAttribute("aria-hidden","true")};openButton.addEventListener("click",event=>{event.preventDefault();isOpen?close():open()});closeButton.addEventListener("click",close);input.addEventListener("input",updateSend);input.addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){
event.preventDefault();if(!send.classList.contains("is-disabled"))send.click()}});send.addEventListener("click",event=>{if(send.classList.contains("is-disabled")){event.preventDefault();input.focus();return}addMessage(input.value.trim(),true);input.value="";updateSend()
;window.setTimeout(close,reducedMotion?0:350)});document.addEventListener("click",event=>{const trigger=event.target.closest('[data-whatsapp-compose],a[href*="wa.me/"]');if(trigger&&!widget.contains(trigger)){event.preventDefault();let prefill=trigger.dataset.whatsappMessage||""
;const href=trigger.closest("a[href]")?.getAttribute("href")||"";try{prefill=new URL(href,window.location.href).searchParams.get("text")||prefill}catch(_){}open(prefill);return}if(isOpen&&!widget.contains(event.target))close()});window.addEventListener("marzoft:close-whatsapp-composer",close);(async()=>{try{
const api=window.marzoftBackend||window.MarzoftSupabase||window.AdminAPI;const config=typeof api?.getConfig==="function"?await api.getConfig():null;const configuredPhone=config?.settings?.waNumber||config?.settings?.whatsappNumber||config?.whatsappNumber;if(configuredPhone){
phone=String(configuredPhone).replace(/\D/g,"")||defaultPhone;updateSend()}}catch(_){}})();updateSend()})();